name: Kindling
options:
  bundleIdPrefix: com.shimondeitel.kindling
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Kindling:
    type: application
    platform: iOS
    sources:
      - path: Kindling
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.kindling
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Kindling/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  KindlingTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: KindlingTests
      - path: Kindling.storekit
    dependencies:
      - target: Kindling
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.kindling.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  KindlingUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: KindlingUITests
    dependencies:
      - target: Kindling
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.kindling.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Kindling:
    build:
      targets:
        Kindling: all
        KindlingTests: [test]
        KindlingUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Kindling.storekit
    test:
      config: Debug
      storeKitConfiguration: Kindling.storekit
      targets:
        - KindlingTests
        - KindlingUITests
    archive:
      config: Release
